name: witt
description: Simple state management powered by ValueNotifier with depedency injection.
version: 0.1.0
repository: https://github.com/edsulaiman/witt

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
