name: witt
description: Simple state management powered by ValueNotifier with service locator.
version: 0.6.0
repository: https://github.com/edsulaiman/witt

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
