name: we_it
description: Core library, powered by get_it and value_notifier.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
